<MainWin>:
    name:"main"
    textinput:textinput.__self__
    canvas.before:
        Color:
            rgba: 100,100,100,0.15
        Rectangle:
            pos: self.pos
            size: self.size
    FloatLayout:
        Label:
            size_hint_y: 0.12
            pos_hint: {"x":0, "top":0.70}
            text: "Plese enter filepath: "
            font_size: (root.width + root.height) / 8**2
            text_size:self.size
            halign:"left"

        TextInput:
            id:textinput
            focus:True
            pos_hint: {"x":0, "top":0.57}
            size_hint:None,None
            width:root.width*(2/3)
            size_hint_y:0.07
            multiline: False
            font_size: (root.width + root.height) / 8**2

        Button:
            size_hint:None,None
            pos_hint: {"x":0.665, "top":0.569}
            width: root.width*(1/3)
            size_hint_y:0.07
            font_size: (root.width + root.height) / 8**2
            text: "Open File"
            on_press: root.toSecond(0)

<Win2>
    name: "second"
    canvas.before:
        Color:
            rgba: 100,100,100,0.15
        Rectangle:
            pos: self.pos
            size: self.size

    FloatLayout:
        Button:
            size_hint:None,None
            pos_hint: {"x":0.25, "top":0.20}
            width: root.width*(1/4)
            size_hint_y:0.07
            font_size: (root.width + root.height) / 8**2
            text: "OK"
            on_press: root.openFile(filechooser.selection)

        Button:
            size_hint:None,None
            pos_hint: {"x":0.50, "top":0.20}
            width: root.width*(1/4)
            size_hint_y:0.07
            font_size: (root.width + root.height) / 8**2
            text: "Quit"
            on_press: root.toMain()

        FileChooserIconView:
            id:filechooser
            pos_hint: {"x":0, "top":1.0}
            size_hint_y:0.7

